### ISSUE TITLE
submenu can disable?

### ISSUE THREAD

**Issue by kiam123** [iakmds/menu_bar#1]
i can disable submenu button?

![image](https://user-images.githubusercontent.com/14953180/230963784-1fac9f6f-7d9a-41da-b2d1-050b76dcacaa.png)

**Comment by iakdis** [comment]
Hi,
does it work if you use `null` for the `onTap` field of the MenuButton? For example:

```dart
BarButton(
    text: const Text('Help', style: TextStyle(color: Colors.white)),
    submenu: SubMenu(
        menuItems: [
            MenuButton(
              text: const Text('View License'),
              onTap: null, <------------------------------------------------------------------------------
            ),
            MenuButton(
              text: const Text('About'),
              onTap: null, <------------------------------------------------------------------------------
            ),
        ],
    ),
),
```

**Comment by kiam123** [comment]
This means that I need to implement the enable and disable functions for the Text widget?

**Comment by iakdis** [comment]
Does it do that automatically? If not, unfortunately you'd have to do it manually. An "enabled" option could be implemented in the future though

**Comment by kiam123** [comment]
> Hi, does it work if you use `null` for the `onTap` field of the MenuButton? For example:
> 
> ```dart
> BarButton(
>     text: const Text('Help', style: TextStyle(color: Colors.white)),
>     submenu: SubMenu(
>         menuItems: [
>             MenuButton(
>               text: const Text('View License'),
>               onTap: null, <------------------------------------------------------------------------------
>             ),
>             MenuButton(
>               text: const Text('About'),
>               onTap: null, <------------------------------------------------------------------------------
>             ),
>         ],
>     ),
> ),
> ```

yes, this solved my problem, thanks for your quick reply
