### ISSUE TITLE
[New Feature] Navigation using Arrow Keys

### ISSUE THREAD

**Issue by KaushikGupta007** [iakmds/menu_bar#2]
Hello there,
Please add support for Menu Navigation using Arrow keys(left and right) and Submenu Navigation using Arrow keys(up and down). This will be really appreciated.
Thanks

**Comment by iakdis** [comment]
Hi, sorry for the late response.

It should be working with the latest version (0.5.0) once you open the menu bar. Let me know if it works for you!

**Comment by iakdis** [comment]
@KaushikGupta007 did it work? Can I close this issue? :smiley:
