### ISSUE TITLE
No icon on menu with submenu

### ISSUE THREAD

**Issue by marianodrz** [iakmds/menu_bar#4]
Hi, first of all i want to thank you for this great package. 

Im having trouble to display icon in a menu with submenu. Even if i try the example on the page.
As seen in the image below the "Preferences" or "Change Theme" have icon and submenu, but when I run it they have only text. 
The icons are shown when the menu doesnt have submenus without any trouble.

![imagen](https://github.com/iakmds/menu_bar/assets/9516598/4db5bd34-4338-4c20-b7fa-26117f9b02ee)

Is it something that has been deprecated or just a bug?.

Regards.

**Comment by iakdis** [comment]
Hi @marianodrz,

thank you a lot for the issue! You are right, as there was a line missing to display the icon in a submenu button.

I have now uploaded a new version 0.5.3 to [pub.dev](https://pub.dev/packages/menu_bar). Let me know, if it worked for you. This is the result before and after:

![before](https://github.com/iakmds/menu_bar/assets/111225446/62acbba5-7d14-4530-af7b-8882a8b6f1c5)
![after](https://github.com/iakmds/menu_bar/assets/111225446/4fefd392-a303-4ea0-b24d-3ddb41dc3b89)

**Comment by marianodrz** [comment]
Hi @iakmds,

I've tested the new version and now it works great 😄.

Thx for the effort. Nice package.
